version: '3.9'

services:
  mockserver:
    image: mockserver/mockserver
    volumes:
      - ./mockserver/:/config/
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json

  kong:
    image: kong:2.6.0
    container_name: kong
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    volumes:
      - ./kong/:/home/kong/
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    depends_on:
      - mockserver

  konga:
    image: pantsel/konga
    ports:
      - 1337:1337
    volumes:
      - ./konga/:/app/konga/seed/
    environment:
      NO_AUTH: 'true'
      KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE: "/app/konga/seed/kong_node.data"
    depends_on:
      - kong

networks:
  default:
    name: kong-net
    driver: bridge
